import type { Metadata } from "next";


import Navbar from "../components/students/Navbar";
import Footer from "../components/students/Footer";


export const metadata: Metadata = {
  title: "Menty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<div>

        <Navbar/>
        {children}
        <Footer/>
</div>
      

  );
}
