name: dockerhub-frontend-service

on:
  push:
    branches: [ "main" ]
    paths: ["/**"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build --build-arg JWT_KEY=${{ secrets.JWT_KEY }} -t harishk2001/menty-frontend-service .
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker push harishk2001/menty-frontend-service
